# Generated by Django 5.2 on 2025-04-07 07:33

import django.contrib.auth.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GPT', '0004_remove_member_validate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='department_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AddField(
            model_name='applications',
            name='member',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='member',
            name='application',
            field=models.ManyToManyField(related_name='members', to='GPT.applications'),
        ),
        migrations.AlterField(
            model_name='member',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='member',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username'),
        ),
        migrations.DeleteModel(
            name='Department',
        ),
    ]
